version: '3.9'

services:
  database_build:
    image: postgres
    container_name: db_build
    volumes: 
      - db_data_build:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: Kenough321
      POSTGRES_USER: postgres
    env_file:
      - ./db/.env
    networks:
      - backend-network

  frontend_build:
    container_name: frontend_build
    build:
      context: ./client/filmstrip
      dockerfile: prod.Dockerfile
    ports:
      - 80:80
    networks:
      - frontend-network

  backend1:
    container_name: backend1
    hostname: backend1
    build:
      context: ./server
      dockerfile: prod.Dockerfile
    env_file:
      - ./server/.env
    ports:
      - 3001:3001
    networks:
      - backend-network
      - frontend-network
  
  backend2:
    container_name: backend2
    hostname: backend2
    build:
      context: ./server
      dockerfile: prod.Dockerfile
    env_file:
      - ./server/.env
    ports:
      - 3002:3001
    networks:
      - backend-network
      - frontend-network

  backend3:
    container_name: backend3
    hostname: backend3
    build:
      context: ./server
      dockerfile: prod.Dockerfile
    env_file:
      - ./server/.env
    ports:
      - 3003:3001
    networks:
      - backend-network
      - frontend-network

volumes:
  db_data_build:

networks:
  backend-network:
    ipam:
      config:
        - subnet: 172.38.109.0/24
          gateway: 172.38.109.1
  frontend-network:
    ipam:
      config:
        - subnet: 172.58.109.0/24
          gateway: 172.58.109.1
