services:
  database:
    image: postgres
    container_name: db
    volumes: 
      - ./db/db.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: Kenough321
      POSTGRES_USER: postgres
    env_file:
      - ./db/.env
  backend:
    container_name: backend
    build:
      context: ./server
      dockerfile: Dockerfile
    env_file:
      - ./server/.env
    volumes:
      - /app/node_modules
      - ./server:/app
    ports:
      - 3001:3001
  frontend:
    container_name: frontend
    build:
      context: ./client/filmstrip
      dockerfile: Dockerfile
    volumes:
      - ./client/filmstrip/src:/app/src
      - ./client/filmstrip/public:/app/public
      - /app/node_modules
    ports:
      - 3000:3000
    environment:
      - WDS_SOCKET_HOST=127.0.0.1 
      - CHOKIDAR_USEPOLLING=true
      - WATCHPACK_POLLING=true